# Generated by Django 3.1.3 on 2020-11-03 08:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuaryDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=250)),
                ('state', models.CharField(choices=[('ACT', 'ACT'), ('QLD', 'QLD'), ('NSW', 'NSW'), ('SA', 'SA'), ('VIC', 'VIC'), ('TAS', 'TAS')], default='VIC', max_length=10)),
                ('manager_name', models.CharField(max_length=20)),
                ('manager_email', models.EmailField(max_length=20)),
                ('manager_phone', models.CharField(max_length=10)),
                ('supervisor_name', models.CharField(max_length=20)),
                ('supervisor_email', models.EmailField(max_length=20)),
                ('supervisor_phone', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SpareParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=250)),
                ('vendor_name', models.CharField(max_length=20)),
                ('vendor_status', models.CharField(choices=[('international', 'international'), ('local', 'local')], default='international', max_length=20)),
                ('weight_kg', models.CharField(max_length=20)),
                ('machine', models.CharField(max_length=20)),
                ('model_number', models.CharField(max_length=20)),
                ('aud', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-vendor_status',),
            },
        ),
    ]
