# Generated by Django 3.1.3 on 2020-11-16 11:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuaryDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=250)),
                ('state', models.CharField(choices=[('ACT', 'ACT'), ('QLD', 'QLD'), ('NSW', 'NSW'), ('SA', 'SA'), ('VIC', 'VIC'), ('TAS', 'TAS')], default='VIC', max_length=10)),
                ('manager_name', models.CharField(blank=True, max_length=20, null=True)),
                ('manager_email', models.EmailField(blank=True, max_length=50, null=True)),
                ('manager_phone', models.CharField(blank=True, max_length=10, null=True)),
                ('supervisor_name', models.CharField(blank=True, max_length=20, null=True)),
                ('supervisor_email', models.EmailField(blank=True, max_length=50, null=True)),
                ('supervisor_phone', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SpareParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('vendor_status', models.CharField(blank=True, choices=[('international', 'international'), ('local', 'local')], default='international', max_length=200, null=True)),
                ('sp_type', models.CharField(blank=True, choices=[('ground engaging tools', 'ground engaging tools'), ('manganese liners', 'manganese liners'), ('mechanical parts', 'mechanical parts')], default='mechanical parts', max_length=50, null=True)),
                ('weight_kg', models.CharField(blank=True, max_length=20, null=True)),
                ('machine', models.CharField(blank=True, max_length=50, null=True)),
                ('model_number', models.CharField(blank=True, max_length=50, null=True)),
                ('aud', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('usd', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-vendor_status',),
            },
        ),
        migrations.CreateModel(
            name='SpareParts_two',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=20, null=True)),
                ('vendor_status', models.CharField(blank=True, choices=[('international', 'international'), ('local', 'local')], default='international', max_length=20, null=True)),
                ('sp_type', models.CharField(blank=True, choices=[('ground engaging tools', 'ground engaging tools'), ('manganese liners', 'manganese liners'), ('mechanical parts', 'mechanical parts')], default='mechanical parts', max_length=50, null=True)),
                ('weight_kg', models.CharField(blank=True, max_length=20, null=True)),
                ('machine', models.CharField(blank=True, max_length=20, null=True)),
                ('model_number', models.CharField(blank=True, max_length=20, null=True)),
                ('aud', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('usd', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('part_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.spareparts')),
            ],
            options={
                'ordering': ('-vendor_status',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=20, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('quantity', models.IntegerField()),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('pr_number', models.CharField(blank=True, max_length=8, null=True)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('site_name', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('site_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.quarydetail')),
            ],
        ),
    ]
