# Generated by Django 3.1.3 on 2020-11-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarydetail',
            name='manager_email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quarydetail',
            name='supervisor_email',
            field=models.EmailField(max_length=50),
        ),
    ]
