# Generated by Django 3.1.3 on 2020-11-16 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_auto_20201116_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='site_id',
        ),
    ]
