# Generated by Django 3.1.3 on 2020-11-17 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_remove_order_site_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.date(2020, 11, 17)),
        ),
    ]
