# Generated by Django 3.1.3 on 2020-11-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_auto_20201103_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spareparts',
            name='machine',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='model_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='weight_kg',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
