# Generated by Django 3.1.3 on 2020-11-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_auto_20201104_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='spareparts',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='spareparts',
            name='usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='aud',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
