# Generated by Django 3.1.3 on 2020-11-10 22:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, choices=[('Steel Trough Roller', 'Steel Trough Roller'), ('Steel Return Roller', 'Steel Return Roller'), ('HDPE Trough Roller', 'HDPE Trough Roller'), ('HDPE Return Roller', 'HDPE Return Roller'), ('Impact Roller', 'Impact Roller')], default='Steel Trough Roller', max_length=50, null=True)),
                ('roller_diameter', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('wall_thickness', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('roller_length', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('shaft_diameter', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('bearing', models.CharField(blank=True, max_length=20, null=True)),
                ('aud', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('usd', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-description',),
            },
        ),
    ]
